spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: audit-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


topic-to-send-message: audit-topic
topic-to-consume-message: ${topic-to-send-message}